### ISSUE TITLE
add it to f-droid

### ISSUE THREAD

**Issue by 6543** [iNPUTmice/lttrs-android#10]

**Comment by iNPUTmice** [comment]
I’m considering it too early to make Ltt.rs available to a general public. In it’s current state it is aimed at developers.

Aside from that Ltt.rs will be made available on F-droid as a reproducible build that is signed with my key when the time comes.

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6389
