### ISSUE TITLE
Support mailto: links

### ISSUE THREAD

**Issue by iNPUTmice** [iNPUTmice/lttrs-android#12]

**Comment by cketti** [comment]
`mailto:` URIs can contain much more information than just a single email address. See [RFC 6068](https://tools.ietf.org/html/rfc6068). 
Example: `mailto:joe@example.com?cc=bob@example.com&body=hello`

For testing you could use the sample app in [cketti/EmailIntentBuilder](https://github.com/cketti/EmailIntentBuilder).

The Android platform contains the [MailTo](https://developer.android.com/reference/android/net/MailTo.html) class to decode `mailto:` URIs. Unfortunately, it is buggy and doesn't properly decode more complex URIs. You'll probably want to go with your own code. K-9 Mail's implementation for inspiration: [MailTo.java](https://github.com/k9mail/k-9/blob/706b13ba714e58c61f0cbcc3c4d7c4407ab82251/app/core/src/main/java/com/fsck/k9/helper/MailTo.java)

**Comment by wiktor-k** [comment]
Another not-so-rare `mailto` parameter is `in-reply-to` as quoted from cketti's link:

```
   An interesting use of 'mailto' URIs occurs when browsing archives of
   messages.  A link can be provided that allows replying to a message
   and conserving threading information.  This is done by adding an
   In-Reply-To header field containing the Message-ID of the message
   where the link is added, for example:

   <mailto:list@example.org?In-Reply-To=%3C3469A91.D10AF4C@
   example.com%3E>
```

It's used in sr.ht forge to achieve correct threading. For example this link: https://lists.sr.ht/~sircmpwn/sr.ht-discuss/%3C86k14d3d6t.wl-tim%40datenknoten.me%3E after login contains the "Reply to thread" button with the following link target (domains replaced with `example.com`):

```
mailto:~sircmpwn/sr.ht-discuss@lists.sr.ht?cc=Tim%20Schumacher%20%3Ctim%40example.com%3E&in-reply-to=%3C86k14d3d6t.wl-tim%40example.com%3E&subject=Re%3A%20builds.sr.ht%20job%20error%20handling
```

This is correctly supported by, for example, Thunderbird (even if there are no visual cues).
