### ISSUE TITLE
F droid build not installable

### ISSUE THREAD

**Issue by driftywinds** [iNPUTmice/lttrs-android#126]
The latest version on f droid does not install and says wrong file format

**Comment by licaon-kter** [comment]
I tested only that it builds reproducibly...

**Comment by licaon-kter** [comment]
The verified APK can't be installed either: https://ltt.rs/fdroid/repo/Ltt.rs-0.2.3-fdroid-release.apk :(

**Comment by FestplattenSchnitzel** [comment]
> The verified APK can't be installed either: https://ltt.rs/fdroid/repo/Ltt.rs-0.2.3-fdroid-release.apk :(

Hmm, install works fine for me on FP2, /e/ Android 9.

**Comment by licaon-kter** [comment]
No v2 signature, since when they started to enforce that?

**Comment by iNPUTmice** [comment]
Ltt.rs 0.2.4 has finally been released on F-Droid (after problems with reproducible builds). This should install fine.
