### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by licaon-kter** [iNPUTmice/lttrs-android#14]
I recommend https://hosted.weblate.org/ as Crowdin and Transifex are proprietary and have dubious terms.

**Comment by iNPUTmice** [comment]
I’ve asked weblate to host this open source project for free in late February and I haven’t heard back yet.

**Comment by licaon-kter** [comment]
At what address?

**Comment by iNPUTmice** [comment]
No address. There was a web form available here: https://hosted.weblate.org/hosting/ that I filled out.
This automatically created an issue on their support tracker (that I’m not able to access with my weblate credentials it seems.) - But no reaction since.

**Comment by orangesunny** [comment]
Hi, I am sorry for the waiting. That was not a problem of a bad address, but my overload. The project is now set up. Welcome in a community, and keep up with good work!

Translate happy, translate libre! 😍

**Comment by licaon-kter** [comment]
https://hosted.weblate.org/projects/ltt-rs/
