### ISSUE TITLE
Fastmail no longer supports app passwords

### ISSUE THREAD

**Issue by DIWesser** [iNPUTmice/lttrs-android#153]
I emailed Fastmail support about the "Wrong password. Try again." error. Here's what they said:

> I'm sorry about the confusion caused here. We used to use app passwords for JMAP but we now use [API tokens](https://www.fastmail.help/hc/en-us/articles/5254602856719-API-tokens).
>
> More information regarding JMAP can be found [here](https://www.fastmail.com/developer/).

I've tried using the API url (`https://api.fastmail.com/jmap/session`) as the connection URL instead of the one listed in the readme for this repo. It worked, but plugging in an API token as a password isn't working.

**Comment by rjbs** [comment]
Hello from Fastmail!

To use an API token, the app will need to switch from using Basic auth to Bearer auth, not just change the API URL.  This should be simple.

*That said*, it'd be much better to not use API tokens, but instead use OAuth.  To get set up for that, [get in touch with us](https://www.fastmail.help/hc/en-us/articles/4951369076879-Partnering-with-Fastmail).  We like helping make Fastmail easier to use!

**Comment by lordearl** [comment]
Yes I'd like Fastmail to work again with Ltt.rs
Hopefully there will be an update to the app soon?

**Comment by JakeHL** [comment]
Doesn't look like anyone has picked up work on this. I'm no android Dev but I'll happily have a crack at this. The change seems very straightforward.

**Comment by lockywolf** [comment]
@jakehl have you had any luck with this?

**Comment by jakehl** [comment]
Nope sorry, I moved to iPhone

**Comment by iNPUTmice** [comment]
Development is now happening on [Codeberg](https://github.com/iNPUTmice/lttrs-android) but I've recently added support for Bearer Tokens. This will be released as 0.4.2 soon.
