### ISSUE TITLE
Bypass "Type in a secure URL" (for internal VPN for example)

### ISSUE THREAD

**Issue by pacien** [iNPUTmice/lttrs-android#159]
During the setup, the app asks for a connection URL.

Entering `http://[some internal address` results in the error:
"Type in a secure URL", preventing the user from continuing forward.

There is no security issue with using an `http` endpoint within a company VPN
for example.

I think that a very obvious security warning would be enough.
Preventing the user from continuing at all is problematic for these setups.

**Comment by iNPUTmice** [comment]
This has been discussed here: https://codeberg.org/iNPUTmice/lttrs-android/issues/1
