### ISSUE TITLE
Email sender names starting with non letters have weird avatars

### ISSUE THREAD

**Issue by iNPUTmice** [iNPUTmice/lttrs-android#17]
For example `"IETF Secretariat"` puts the `"` in the avatar which looks odd. Gmail actually just uses a gray profile picture thing.

**Comment by cketti** [comment]
K-9 Mail uses the first letter in the name. See [ContactLetterExtractor](https://github.com/k9mail/k-9/blob/ecec1e1db5d0261646d3d654eb6b82760a0a118d/app/ui/src/main/java/com/fsck/k9/contacts/ContactLetterExtractor.kt).
