### ISSUE TITLE
Explain JMAP-only in settings process

### ISSUE THREAD

**Issue by keunes** [iNPUTmice/lttrs-android#35]
Hello,

I was looking for an alternative to K-9 Mail as it looks & feels a bit old. I came across Lttrs on F-Droid. From the description I didn't see any blocker, as I'm fine with not being able to go fully offline (instead rely on caching).

However, when trying to enter the 'connection url' I got an error. I tried both IMAP and SMTP links of my provider, but neither worked. Looking for an issue on GitHub I discovered that JMAP is a separate thing from IMAP and is required for using the app. This is currently not clear from the app description (in F-Droid). I would suggest therefore to:
- Make the JMAP requirement more explicit, at the beginning of the description
- Mention the JMAP requirement in the error message that appears when a wrong connection URL is set (currently it just mentions 'valid' without specifying what that is).

**Comment by licaon-kter** [comment]
There are 2 mentions of JMAP there,  and to mentions of IMAP or SMTP.
