### ISSUE TITLE
fastmail stops updating

### ISSUE THREAD

**Issue by afonari** [iNPUTmice/lttrs-android#37]
To reproduce:
1. Install and hook up a fastmail.com account
2. After some time ltt.rs stops showing new email

I see app hitting jmap.fastmail.com

**Comment by SamWhited** [comment]
I've had this happen as well, but it doesn't happen every time. I had to reinstall it twice I think and now everything appears to work. Unsure what the difference was the third time.

**Comment by afonari** [comment]
Gotcha, thanks @SamWhited will try.

**Comment by iNPUTmice** [comment]
I'm aware of a bug that occurs when you haven't synchronized for a while
(if the diff becomes too large). This can be a fixed by reinstalling. There
is a bug open for this on the jmap-mua tracker.

If reinstalling doesn't fix the issue we will probably need adb logcat
output.

**Comment by afonari** [comment]
Seems to be working, linking: https://github.com/iNPUTmice/jmap/issues/25

**Comment by iNPUTmice** [comment]
This has been fixed in Ltt.rs 0.1.3

**Comment by SamWhited** [comment]
I recently decided to try ltt.rs again and just FYI this happened for me again after a few days. Pull to refresh and the like doesn't work either and there is no error, it just never updates and gets further and further out of date.
