### ISSUE TITLE
Crowdfunding?

### ISSUE THREAD

**Issue by guettli** [iNPUTmice/lttrs-android#4]
Have you considered to speed up development by crowdfunding?

I would donate some money.

I am sick of the dated SMTP/IMAP protocol and mail user agents.

**Comment by wiktor-k** [comment]
@guettli have you seen that the author is participating in GitHub Sponsors? https://github.com/iNPUTmice

**Comment by iNPUTmice** [comment]
As @wiktor-k pointed out I’m on [Github Sponsors](https://github.com/sponsors/iNPUTmice) and [Liberapay](https://liberapay.com/iNPUTmice). The texts on both pages currently only mention my other project [Conversations](https://github.com/siacs/Conversations/) but will probably be updated to also include Ltt.rs once it reaches a certain level of maturity. In any case it is money that will reach me.

What’s currently slowing down Ltt.rs development is the unclear state of acceptance of JMAP. Meaning I don’t know yet if JMAP will actually become a thing. Dovecot has expressed _interest_ but nothing has actually happened in that regard. And if Dovecot won’t support it, I’m not sure that JMAP will go anywhere.
