### ISSUE TITLE
cannot set username that is not an email address

### ISSUE THREAD

**Issue by streaps** [iNPUTmice/lttrs-android#43]
My username on the cyrus server is just username and not username@domain.tld, but I cannot configure it in ltt.rs. It always send the full email address for authentication, which doesn't work.

**Comment by iNPUTmice** [comment]
In Cyrus using usernames that do not contain the domain is no longer the recommended method and might become the only supported method.
https://github.com/cyrusimap/cyrus-imapd/issues/2847

Maybe @chibenwa can say something about the situation in Apache James. Are plain usernames a valid way to login?

If not I’ll probably just close here.

**Comment by chibenwa** [comment]
Like `user` instead of `user@domain.tld` ?

That's not the preferred way to do it, but you can configure James to do so, yes. That then just depends of your configuration, but it is not enabled by default.

**Comment by iNPUTmice** [comment]
> Like `user` instead of `user@domain.tld`?

Yes.

OK. I’m closing here for now.

**Comment by streaps** [comment]
Why close it? It is a valid login/username option in Cyrus.

**Comment by iNPUTmice** [comment]
@streaps see the issue I’m referencing. It's not a recommended setup for Cyrus and will probably no longer work for future versions of Cyrus.
