### ISSUE TITLE
Test / Promote ways to use Ltt.rs without a JMAP server

### ISSUE THREAD

**Issue by marclaporte** [iNPUTmice/lttrs-android#46]
Going all-in JMAP is the best. But as a transition, maybe proxies could be tested and promoted?

https://github.com/barnslig/jmap-proxy
https://github.com/filiphanes/jmap-proxy-python
https://github.com/jmapio/jmap-perl

**Comment by iNPUTmice** [comment]
I’m going to focus my energy on developing Ltt.rs and testing this against Cyrus and my own mock server. But you are welcome to test this and amend the README.
