### ISSUE TITLE
Why not a PWA?

### ISSUE THREAD

**Issue by guettli** [iNPUTmice/lttrs-android#5]
I dream of a new mail user agent which works on Desktop and on mobile plattforms.

Why did you use Android Jetpack and not  a progressive web app?

**Comment by iNPUTmice** [comment]
I don’t like web apps. They are slow and don’t feel native anywhere.
That being said I also want a desktop client for myself and therefor vasts parts of the code base are plattform independend with the goal in mind to also create [lttrs-cli](https://github.com/iNPUTmice/lttrs-cli) which is havily inspired by [sup](https://sup-heliotrope.github.io/) which in turn is basically Gmail for the console.
