### ISSUE TITLE
LTT.RS crashes on 'cannotCalculateChanges'

### ISSUE THREAD

**Issue by chibenwa** [iNPUTmice/lttrs-android#50]
To enable LTTRS support on James I came up with naive implementations of \*/changes methods by just returning cannotCalculateChanges errors.

LTT.RS crashes if these errors are returned (no email loaded)

Expectations: This should not affect the initial loading, but only the refresh. Maybe LTTRS should uncorrelated /changes calls from the initial loading? 

This would enable a non-lying naive implementation.

Note that fully implemented servers might return these errors ie if the states requested are too old.

**Comment by iNPUTmice** [comment]
This ~is~ was tracked here: https://github.com/iNPUTmice/jmap/issues/25

Related to #37

**Comment by chibenwa** [comment]
:+1:

**Comment by iNPUTmice** [comment]
This has been fixed in Ltt.rs 0.1.3
