### ISSUE TITLE
Making core capability mandatory

### ISSUE THREAD

**Issue by rouazana** [iNPUTmice/lttrs-android#55]
Hello,

As discussed on the JMAP mailing list https://mailarchive.ietf.org/arch/msg/jmap/wQaw_ivbvFtOrEPbkkOkDp3OGrU/ could you systematically add the `urn:ietf:params:jmap:core` capability in the `using` parameters?

Thanks,
Raphaël.

**Comment by iNPUTmice** [comment]
Fixed in 2ae0e80ebfb356e45ae51ecd75359ab9e7d4f77e
