### ISSUE TITLE
Attachment handling

### ISSUE THREAD

**Issue by iNPUTmice** [iNPUTmice/lttrs-android#59]
* Available attachments should be shown underneath emails in the thread view
* Ability to download attachments
  * To interntal storage (by default)
  * Save on SD card on user request
* Attachment handling for outgoing/drafting email

**Comment by chibenwa** [comment]
> Available attachments should be shown underneath emails in the thread view

We had the exact same UX rules, and people complained not easily seeing attachments, especially when they are attached to a mail in a thread with 30+ relies.

I would advise to position the attachment list below the headers but above the body.

Cheers

**Comment by iNPUTmice** [comment]
Fixed in 8b04079a3c382a384f9730ec3a2ce0f7c16620e9...7225e5c31bdbf39d97e4840d98e83754a9f52ca2
