### ISSUE TITLE
Use Theme.MaterialComponents.DayNight.NoActionBar as Base Theme

### ISSUE THREAD

**Issue by iNPUTmice** [iNPUTmice/lttrs-android#6]
If we support this early it will hopefully be less of a pain later.

This means using `?colorSurfce` and `?colorOnSurfce` through out the app.

Find more information here: [Dark theme](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme) and [Color Theming](https://material.io/develop/android/theming/color/).

**Comment by licaon-kter** [comment]
Isn't it [this](https://github.com/bilde2910/Hauk/commit/be6cee8f1f64602ac505b79e6d925f3c566d4e0f) easy to setup?

**Comment by iNPUTmice** [comment]
> Isn't it this easy to setup?

Yes and no. It is if the app is not hard coding text and background colors. This issue acts as a reminder not to do that.

**Comment by iNPUTmice** [comment]
There are still some issues with Dark Theme (drop shadows not rendering correctly in identity selector for example) but in general this issue can be considered done.
