### ISSUE TITLE
Autocrypt support

### ISSUE THREAD

**Issue by iNPUTmice** [iNPUTmice/lttrs-android#62]
* Integrate Autocrypt into setup process
* Show autocrypt status in draft email screen.

**Comment by iNPUTmice** [comment]
> * Integrate Autocrypt into setup process
> * Show autocrypt status in draft email screen.

Those two features are available in current master and will be released with 0.3 soon.

**Comment by xandro0777** [comment]
Surprised you would waste your time on this. The key exchange is *much* worse than TOFU, an attacker can initiate a key exchange any number of times even after initial keys were exchanged. Even a correctly encrypted and signed message can contain malicious new keys in its headers. The standard even recommended that new keys are accepted without even notifying the user. The dream of any MITM.

https://mail.mozilla.org/pipermail/tb-planning/2019-December/007318.html

**Comment by r10s** [comment]
the idea of Autocrypt is not mainly to replace _encrypted_ messages but to replace _unencrypted_ messages. nothing prevents implementations to add additional checks on top of Autocrypt.
