### ISSUE TITLE
Can't access Fastmail account, get "Wrong password. Try again." error

### ISSUE THREAD

**Issue by r0bbie** [iNPUTmice/lttrs-android#68]
I'm running latest version 0.1.4 from the F-Droid repo.

On install, I provide my Fastmail email address, the connection URL (https://jmap.fastmail.com/.well-known/jmap), and then get to the password screen. I can't seem to get the app to accept my password, repeatedly getting a wrong password error. I've tried both an app password I set for this, and just in case also tried my main Fastmail password (which predictably didn't work, and I got an automated email from Fastmail a minute later informing me I'd been trying to sign into a JMAP client with a non-app password).

I've made absolutely sure I'm providing the correct app password (and Fastmail login email address), but can't get in.

**Comment by iNPUTmice** [comment]
I realize that this is not the most helpful thing to say but it works for me. (With Fastmail and a JMAP specific app password.)

Maybe try with `curl` against the well-known address (A simple, authenticated GET should do.) and if this doesn’t work either you have a reason to contact Fastmail support.

**Comment by r0bbie** [comment]
I've tried again with a JMAP specific app password, and it does seem to have worked this time. I don't recall if I seen that as an option or not previously (seems curious I would have missed that!) but in any case whether due to my error or an issue on Fastmail's side, does now seem to be resolved!

**Comment by DIWesser** [comment]
Turns out fastmail doesn't support app passwords for JMAP anymore. [I've opened a new issue.](https://github.com/iNPUTmice/lttrs-android/issues/153)
