### ISSUE TITLE
Unable to create or delete a mailbox from the app

### ISSUE THREAD

**Issue by davek1963** [iNPUTmice/lttrs-android#73]
There is no mechanism for creating or deleting a mailbox

**Comment by afonari** [comment]
I second this. It would b good to implement some sort of account remove. Otherwise I need to uninstall and install app again when bugs like these show up: https://github.com/iNPUTmice/lttrs-android/issues/37

**Comment by iNPUTmice** [comment]
Create is handled by #24

Delete is covered by #85
