### ISSUE TITLE
Increase contrast in quotations in dark theme

### ISSUE THREAD

**Issue by wiktor-k** [iNPUTmice/lttrs-android#8]
Dark green and red text is hardly readable on dark theme:

![2c508b6f_QQalqbLkUONcPfhk0xvmdSmnP5e3ueHuXBUELRgvsDM](https://user-images.githubusercontent.com/1718963/71548848-7874e400-29b4-11ea-9f54-b24e67bf22eb.jpg)

**Comment by iNPUTmice** [comment]
Fixed in e24346d44c6daac50fe2a9437720fcd55d9d4c4e

**Comment by wiktor-k** [comment]
Much, much better! Thank you :+1:
