### ISSUE TITLE
Add the ability to override okhttp config options

### ISSUE THREAD

**Issue by davek1963** [iNPUTmice/lttrs-android#96]
I'd like to adjust the okhttp socket or connection timeout.  
Is it possible to replace the okhttp client or contribute to the builder options?

**Comment by iNPUTmice** [comment]
Ltt.rs won’t have any settings whatsoever. But I’m willing to listen to suggestions on changing the defaults. I haven’t put much thought into those values yet. How are the current values not working for you?

**Comment by davek1963** [comment]
This wasn't meant to be about exposing this to the end user.  Considering the nature of a single jmap request to have n method calls, that previously were n requests.  Previously each method call had socketTimeout time to respond.  Now each method call has 1/n socketTimeout to respond.   The likelihood for a response to fail and the client to be in a bad state are considerable.
